### ISSUE TITLE
 i inserted 8 records and successfully print on jupyter but dont know how to apply this query.Print only those records where salary > 10000  and write this data into salary.csv file.Do all this task from python.

### ISSUE THREAD

**Issue by 23bca275** [vtcbca/internal-exam-23bca275#2]
![Screenshot (10)](https://github.com/user-attachments/assets/6e5219c9-67c7-47b4-9c15-56248d7e55aa)

**Comment by 23bca274** [comment]
create cursor for this and then print salary>10000

**Comment by amitvtcbb** [comment]
as per 23bca274, use cursor and apply select query with where clause. store output in one variable. create any csv file using open function and write this variable using writer object in csv file.

**Comment by 23bca275** [comment]
ok thankyou sir
