### ISSUE TITLE
please solve this error

### ISSUE THREAD

**Issue by 23bca275** [vtcbca/internal-exam-23bca275#3]
![Screenshot (11)](https://github.com/user-attachments/assets/46ab7a26-2b22-4b7c-8c1e-dd90979b1473)

**Comment by 23bca286** [comment]
where condition is wrong.

**Comment by 23bca275** [comment]
Ok thanks

**Comment by 23bca274** [comment]
Do as following : 
1. import sqlite3 and csv
2. connect to the sqlite3 and create cursor
3. write creating table query in cursor.execute() and then execute that query 
4. insert records by using cursor.execute() then fetchall records and print
5. write your main query to print salary > 10000 by using cursor.execute() and print data
6. write records to csv file "w"
7. reade that csv file "r"

NOTE  : DO ALL THIS TASK FROM PYTHON DON'T USE SQLITE3 DATABASE TO CREATE TABLE AND INSERT RECORDS !  

I hope these steps will help you out .

**Comment by 23bca275** [comment]
ok thankyou

**Comment by 23bca275** [comment]
now you can check my program

**Comment by 23bca274** [comment]
> now you can check my program

Please upload your code not the photo

Not able to understand the code from the photo that is too blur !

**Comment by 23bca275** [comment]
now check

**Comment by 23bca274** [comment]
> now check

Please upload your text file or .py file , so I can review your program
